# generated by create_template.py
from config.BERT_GUG.const import *
from config.BERT_GUG.datapath import *
from utils.set_local_const import set_local_const

DEVICE = set_local_const(DEVICE, "cpu")

